import { getReferenceNumber } from "utils/forms-util";

const fields = {
  applicantName: "",
  district: "",
  constituency: "",
  ward: "",
  zone: "",
  businessAddress: "",
  registrationDate: "",
  organiseSimilarEvents: "",
  similarExperience: "",
  mainProblems: "",
  problemAddressed: "",
  projectIdentification: "",
  communityBenefit: "",
  jobsCreated: "",
  takenOutLoan: false,
  firstLoanAndOrganisation: "",
  secondLoanAndOrganisation: "",
  loanStatus: "",
  bankName: "",
  bankBranch: "",
  branchCode: "",
  swiftCode: "",
  accountNumber: "",
  tpin: "",
  mobileMoney: "",
  numberOfMembersTrained: "",
  training: "",
  members: "",
  firstApplicantName: "",
  firstApplicantPhysicalAddress: "",
  firstApplicantPhone: "",
  firstApplicantNrc: "",
  firstApplicantDateSigned: "",
  secondApplicantName: "",
  secondApplicantPhysicalAddress: "",
  secondApplicantPhone: "",
  secondApplicantNrc: "",
  secondApplicantDateSigned: "",
  userId: localStorage.getItem('userId'),
  dateCreated: "",
  status: 0,
  referenceNo: getReferenceNumber(),
};

export { fields };
