import { getReferenceNumber } from "utils/forms-util";

const fields = {
  communityName: "",
  district: "",
  constituency: "",
  ward: "",
  zone: "",
  landTitle: "",
  projectType: "",
  numberBeneficiary: "",
  communityBasedProjects: "",
  comunityFunding: "",
  mainProblems: "",
  problemAddressed: "",
  projectIdentification: "",
  doneBefore: "",
  doneBeforeExplaination: "",
  beneficiaries: "",
  estimatedCost: "",
  communityContribution: "",
  committeMembers: "",
  communitySustainability: "",
  nameProjectProposer: "",
  nrcProjectProposer: "",
  addressProjectProposer: "",
  phoneProjectProposer: "",
  dateSignedProposer: '',
  nameProjectSeconder: "",
  nrcProjectSeconder: "",
  addressProjectSeconder: "",
  phoneProjectSeconder: "",
  dateSignedSeconder: "",
  userId: localStorage.getItem('userId'),
  dateCreated: "",
  status: 0,
  referenceNo: getReferenceNumber(),
};

export { fields };
